#cloud-config
package_update: true
package_upgrade: true

apt:
  sources_list: | 
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-updates main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-backports main restricted universe multiverse
    deb mirror://mirrors.ubuntu.com/mirrors.txt bionic-security main restricted universe multiverse


packages:
 - default-jre            
 - openjdk-11-jre-headless
 - openjdk-8-jre-headless
 - maven
 - python3-distutils
 - apache2-utils

runcmd:
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/etc/motd -o /etc/motd'
 - 'curl -L https://github.com/signalfx/app-dev-workshop/raw/master/apm/java-app.tar.gz -o /run/java-app.tar.gz'
 - tar xvfz /run/java-app.tar.gz -C /home/ubuntu/
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/apm/demo.py -o /home/ubuntu/mypythonapp/demo.py --create-dirs'
 - 'curl https://raw.githubusercontent.com/signalfx/app-dev-workshop/master/apm/post_data.json -o /home/ubuntu/mypythonapp/post_data.json'
 - chown -R ubuntu:ubuntu /home/ubuntu
 - 'curl https://bootstrap.pypa.io/get-pip.py -o /run/get-pip.py'
 - python3 /run/get-pip.py
 - pip install flask requests signalfx-tracing
 - sfx-py-trace-bootstrap
