apiVersion: v1
kind: Service
metadata:
  name: single 
  #  namespace: splunk
spec:
  selector:
    app: splunk 
  ports:
    - name: http
      protocol: TCP
      port: 8000
    - name: hec 
      protocol: TCP
      port: 8088 
