language: python
cache: pip
env:
  global:
    secure: VZOHb2OeqHMjeHhIMN9+9xN5lOU52kvoDtTRFXyOafkZaASOWlkvMBMCShckx4Wi2dChGjCNHe0P/MKWthDvM3RzHT3dzUjYe+K0PBEdPKNv5YX1xkLH03ObmFnjyu/hSvz9LJBzjbV2EkLD50tEk18o1Ix3ekjePbwHpMqenYu+7lph7VUTIy71ClNQXQ8/uIFfSuQ7Blu9FLMQh2mPkZYzQphT1gIQ8D1vof2jLQLu5uIOedmWQWQOms0o0Alw81ts2Ndh+ftxlXeNucqtZaQdxRbfEXhX3X0nJZnE1afGNc+tXb3t4O3RwztWKTZBpwYYsW9O3f4KMh5+JXwNEKBV9T7/IETQCiPKB2VVI7Jvgv5/rWoZYqYU8HuBilaJcQZ0sYt9VL0f2WHve54sZ/V6eWJWplFgaf4yF1RwlisqsxDu2JyQnLSH4ct+3MUFupduc/T5SDQBMsy53Bpk8DVQ/EfdUCjmUWiIG7PvBw60YCjxoXxhHZuKZl6ervG1UBuHV6uRpL4NVh2QIQhrt/p8RQe3slN9R2A8RjsT1GdO85l66HAn/ijnacFjhN+9AW5lyItH0yLCRO447bUZ3ir73lhHi1nj2VRi1yJyb74r7TsF1/veEGP44Jqi+rd1MXkdiTIhladhlp3DVYe6BC5O1+m7sNdOlHNJMjGHkjA=
install:
- pip install -r requirements.txt
script:
- git clean -f -d -x
after_success:
- . ./.ci/deploy.sh
- openssl aes-256-cbc -K $encrypted_5c4519557e13_key -iv $encrypted_5c4519557e13_iv -in app-dev-workshop-deploy-key.enc -out app-dev-workshop-deploy-key -d
- chmod 600 app-dev-workshop-deploy-key
- eval $(ssh-agent -s)
- ssh-add app-dev-workshop-deploy-key
- git config user.name "$GH_USER_NAME"
- git config user.email "$GH_USER_EMAIL"
- git remote set-url origin git@github.com:signalfx/app-dev-workshop.git
- git remote set-branches --add origin gh-pages
- git fetch origin && git fetch origin gh-pages:gh-pages;
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; mkdocs gh-deploy -v --clean -m "$MSG" --remote-name origin ; git push origin gh-pages; fi;
