site_name: 'Splunk App Dev Workshop'
site_description: 'This workshop is going to take you though the exciting journey of App Dev, what this is, why this is important, and how to get started right away!'
site_author: 'Sales Engineering'
site_url: 'https://signalfx.github.io/app-dev-workshop/'
repo_url: 'https://github.com/signalfx/app-dev-workshop/'
edit_uri: 'edit/master/docs/'
copyright: Copyright &copy; 2020 Splunk Inc. All rights reserved.
remote_branch: gh-pages

theme:
  name: material
  palette:
    primary: 'black'
  favicon: images/favicon.ico
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  include_search_page: false
  search_index_only: true
  language: en
  custom_dir: material
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.mark

extra_css:
  - "extra.css"

plugins:
  - git-revision-date-localized:
      type: datetime
      locale: en
  - search
  
nav:
  - '<b>Home</b>': index.md
  - '<b>Introduction</b>': introduction.md
  - '<b>Module 1</b> - Dashboards':
    - 'Working with Dashboards, Charts and Metrics': module1/dashboards.md
  - '<b>Module 2</b> - Detectors':
    - 'Working with Detectors': module2/detectors.md
    - 'Working with Muting Rules': module2/muting.md
  - '<b>Module 3</b> - Smart Agent':
    - 'Deploying the Smart Agent in Kubernetes (K3s)': module3/k3s.md
    - 'Deploying NGINX in K3s' : module3/nginx.md
  - '<b>Module 4</b> - Monitoring as Code':
    - 'Using Terraform for charts and dashboards' : module4/terraform.md
  - '<b>Module 5</b> - Service Bureau':
    - 'Billing and Usage' : module5/service_bureau.md
    - 'Teams' : module5/teams.md
  - '<b>Module 6</b> - µAPM':
    - 'µAPM Architecture Overview': module6/index.md
    - 'Running Hotrod in K3s': module6/hotrod.md
    - 'Running Sock Shop in K3s': module6/sockshop.md
  - '<b>Module 7</b> - VictorOps':
    - 'Coming Soon!': module7/index.md
  - '<b>Post Workshop Clean Up!</b>': module-support/cleanup.md
  - '<b>Optional Modules</b>':
    - 'Running Hotrod in EKS': module8/hotrod-eks.md