apiVersion: v1
kind: Pod
metadata:
  name: redis
  annotations:
    agent.signalfx.com/monitorType.6379: "collectd/redis"
  labels:
    app: sfx-workshop-redis
spec:
  containers:
  - name: redis
    image: redis:4.0.14
    command:
      - redis-server
      - "/redis-master/redis.conf"
    env:
    - name: MASTER
      value: "true"
    ports:
    - containerPort: 6379
    resources:
      limits:
        cpu: "0.1"
    volumeMounts:
    - mountPath: /redis-master-data
      name: data
    - mountPath: /redis-master
      name: config
  volumes:
    - name: data
      emptyDir: {}
    - name: config
      configMap:
        name: example-redis-config
        items:
        - key: redis-config
          path: redis.conf
