# Support for Docker Compose v2, https://docs.docker.com/compose/overview/
version: '2'
services:
  vsplunk:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
      - ./tmp:/tmp
  splunkenterprise:
    #build: .
    hostname: splunkenterprise
    image: splunk/splunk:8.0.1
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_PASSWORD : platano5 
    volumes:
      - ./tmp1:/tmp1
      - ./asdf:/opt/splunk/etc/apps/
#    networks:
#      - bridge
    ports:
      - "8000:8000"
      - "9997:9997"
#      - "8089:8089"
      - "1514:1514"
      - "8088:8088"

networks:
  bridge:
    external:
      name: bridge
